import { useMemo } from 'react'
import { generateIdenticon } from '../lib/identicon'

interface ProxyIdenticonProps {
  address: string
  size?: number
  className?: string
}

export function ProxyIdenticon({
  address,
  size = 32,
  className = '',
}: ProxyIdenticonProps) {
  const svg = useMemo(() => generateIdenticon(address, size), [address, size])

  return (
    <div
      className={`inline-flex items-center justify-center rounded-sm overflow-hidden ${className}`}
      style={{ width: size, height: size }}
      // biome-ignore lint/security/noDangerouslySetInnerHtml: SVG is generated by trusted jdenticon library
      dangerouslySetInnerHTML={{ __html: svg }}
    />
  )
}
